### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ArthurKa** [josh-stillman/lintier#15]
<img width="447" alt="mintty_ygYIuz3jsl" src="https://github.com/josh-stillman/lintier/assets/16370704/beb9634d-efe0-4ec3-afa5-38ee62740a9e">

**Comment by josh-stillman** [comment]
Thanks for flagging, I'll take a look when I get a chance!

**Comment by josh-stillman** [comment]
Heyo - sorry for the long delay.  I've got a young kid now and don't have the same kind of time for personal projects as I used to 😄 .

This should be fixed now in the update I just published.  Try running `npx lintier@latest`.
